### ISSUE TITLE
I can't access with FB or Micrsosoft

### ISSUE THREAD

**Issue by davidbhlm-github** [auth0/sharelock#17]
I have installed your app on my server. When I create a sharelock, I can access using my gmail or twitter account, but I can't access using Microsoft or FB account. I receive this message:  
![screen shot 2015-03-31 at 18 52 42](https://cloud.githubusercontent.com/assets/11521627/6924217/36947142-d7d7-11e4-8cdc-a21a177c5663.png)

The account is right.
Any idea?

Thanks

**Comment by woloski** [comment]
Make sure to check on Auth0 that you want to get back the e-mail. Click
here:

[image: Inline image 1]

And then check Email Addresses
[image: Inline image 2]

**Comment by davidbhlm-github** [comment]
Sorry, have you upload properly the picture? I can't see it.

**Comment by davidbhlm-github** [comment]
But, I have understood you. 
Thank you very much.
